"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.client = exports.settings = void 0;
exports.settings = require('./src/settings');
var callHandler_1 = require("./src/call/callHandler");
var commandHandler_1 = require("./src/commands/commandHandler");
var debug_1 = require("./src/debug/debug");
var Discord = require('discord.js');
exports.client = new Discord.Client();
var token = exports.settings.token;
// const database = require('./database');
// const quotesHandler = require('./src/quotes/Handler');
var prefix = exports.settings.prefix;
exports.client.on('ready', function () {
    callHandler_1.initCallHandler();
    debug_1.initDebugger();
    commandHandler_1.initCommandHandler(prefix);
    console.log('LuciBot Online and listening at prefix: ' + prefix);
});
exports.client.login(token);
